### ISSUE TITLE
project.properties cannot be loaded in Spring Boot native

### ISSUE THREAD

**Issue by gbaso** [aws/amazon-s3-encryption-client-java#158]
When building a S3EncryptionClient, the file `project.properties` is loaded by [`software.amazon.encryption.s3.internal.ApiNameVersion`](https://github.com/aws/amazon-s3-encryption-client-java/blob/main/src/main/java/software/amazon/encryption/s3/internal/ApiNameVersion.java#L36) to get the version. On a native image, `loader.getResourceAsStream("project.properties")` returns null, causing a NullPointerException.

Example repository: https://github.com/gbaso/s3-encryption-client-native

To reproduce, run:

```sh
./mvnw -Pnative native:compile
./target/s3encryption
``` 

which results in:

```log
java.lang.ExceptionInInitializerError: null
        at software.amazon.encryption.s3.materials.KmsKeyring.<clinit>(KmsKeyring.java:32) ~[s3encryption:na]
        at software.amazon.encryption.s3.S3EncryptionClient$Builder.build(S3EncryptionClient.java:696) ~[na:na]
        at com.example.s3encryption.S3encryptionApplication.withS3Client(S3encryptionApplication.java:39) ~[s3encryption:na]
        at com.example.s3encryption.S3encryptionApplication.lambda$0(S3encryptionApplication.java:25) ~[s3encryption:na]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:760) ~[s3encryption:3.0.6]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:750) ~[s3encryption:3.0.6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:317) ~[s3encryption:3.0.6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1304) ~[s3encryption:3.0.6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1293) ~[s3encryption:3.0.6]
        at com.example.s3encryption.S3encryptionApplication.main(S3encryptionApplication.java:19) ~[s3encryption:na]
Caused by: java.lang.NullPointerException: inStream parameter is null
        at java.base@17.0.5/java.util.Objects.requireNonNull(Objects.java:233) ~[na:na]
        at java.base@17.0.5/java.util.Properties.load(Properties.java:407) ~[s3encryption:na]
        at software.amazon.encryption.s3.internal.ApiNameVersion.apiVersion(ApiNameVersion.java:36) ~[na:na]
        at software.amazon.encryption.s3.internal.ApiNameVersion.apiNameWithVersion(ApiNameVersion.java:28) ~[na:na]
        at software.amazon.encryption.s3.internal.ApiNameVersion.<clinit>(ApiNameVersion.java:17) ~[na:na]
        ... 10 common frames omitted
```

Using GraalVM CE 22.3.0 (java 17.0.5) from sdkman.

Please provide [reachability metadata](https://github.com/oracle/graalvm-reachability-metadata) for the necessary resources.

**Comment by justplaz** [comment]
Hi, thanks for raising this issue! The PR https://github.com/aws/amazon-s3-encryption-client-java/pull/161 should fix the issue, and is available in the 3.0.1 release.
